-- Run this in Supabase SQL Editor to create tables for the platform.
-- Subscriptions: one row per user; status 'active' = Pro.

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  stripe_customer_id text,
  stripe_subscription_id text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- If the table already existed with different columns, add the ones we need:
alter table public.subscriptions add column if not exists stripe_customer_id text;
alter table public.subscriptions add column if not exists stripe_subscription_id text;

create index if not exists idx_subscriptions_user_id on public.subscriptions (user_id);
create index if not exists idx_subscriptions_stripe_subscription_id on public.subscriptions (stripe_subscription_id);

-- API keys: store hash only so we can look up user_id by key without storing plain key
create table if not exists public.api_keys (
  id bigint generated by default as identity primary key,
  user_id text not null,
  key_hash text not null unique,
  created_at timestamptz not null default now()
);
alter table public.api_keys add column if not exists user_id text;
alter table public.api_keys add column if not exists key_hash text;
alter table public.api_keys add column if not exists created_at timestamptz default now();
create index if not exists idx_api_keys_user_id on public.api_keys (user_id);
create index if not exists idx_api_keys_key_hash on public.api_keys (key_hash);

-- Reports: pushed from CLI or created in dashboard
create table if not exists public.reports (
  id text primary key,
  user_id text not null,
  project_name text,
  ecosystem text,
  summary text,
  markdown text,
  payload jsonb,
  created_at timestamptz not null default now()
);
alter table public.reports add column if not exists user_id text;
alter table public.reports add column if not exists project_name text;
alter table public.reports add column if not exists ecosystem text;
alter table public.reports add column if not exists summary text;
alter table public.reports add column if not exists markdown text;
alter table public.reports add column if not exists payload jsonb;
alter table public.reports add column if not exists created_at timestamptz default now();
create index if not exists idx_reports_user_id on public.reports (user_id);

-- AI usage: one row per user per month (period = 'YYYY-MM')
create table if not exists public.ai_usage (
  user_id text not null,
  period text not null,
  count int not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, period)
);
alter table public.ai_usage add column if not exists user_id text;
alter table public.ai_usage add column if not exists period text;
alter table public.ai_usage add column if not exists count int default 0;
alter table public.ai_usage add column if not exists updated_at timestamptz default now();

-- Optional: manually grant Pro by inserting a row, e.g.:
-- insert into public.subscriptions (user_id, status) values ('1', 'active') on conflict (user_id) do update set status = 'active', updated_at = now();
